//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowConsoleApplication1.workflowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="workflowService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SecretNumber", ReplyAction="http://tempuri.org/IService/SecretNumberResponse")]
        WorkflowConsoleApplication1.workflowService.SecretNumberResponse SecretNumber(WorkflowConsoleApplication1.workflowService.SecretNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SecretNumber", ReplyAction="http://tempuri.org/IService/SecretNumberResponse")]
        System.Threading.Tasks.Task<WorkflowConsoleApplication1.workflowService.SecretNumberResponse> SecretNumberAsync(WorkflowConsoleApplication1.workflowService.SecretNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SecretNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SecretNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int lower;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int upper;
        
        public SecretNumberRequest() {
        }
        
        public SecretNumberRequest(int lower, int upper) {
            this.lower = lower;
            this.upper = upper;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SecretNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SecretNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int res;
        
        public SecretNumberResponse() {
        }
        
        public SecretNumberResponse(int res) {
            this.res = res;
        }
    }
}
