<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Courses" Member="Courses">
    <Type Name="Course">
      <Column Name="course_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="course_num" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="course_title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="instructor" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cap" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>