#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCourse(Course instance);
  partial void UpdateCourse(Course instance);
  partial void DeleteCourse(Course instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Course> Courses
	{
		get
		{
			return this.GetTable<Course>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Courses")]
public partial class Course : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _course_id;
	
	private System.Nullable<int> _course_num;
	
	private string _course_title;
	
	private string _instructor;
	
	private System.Nullable<int> _cap;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncourse_idChanging(int value);
    partial void Oncourse_idChanged();
    partial void Oncourse_numChanging(System.Nullable<int> value);
    partial void Oncourse_numChanged();
    partial void Oncourse_titleChanging(string value);
    partial void Oncourse_titleChanged();
    partial void OninstructorChanging(string value);
    partial void OninstructorChanged();
    partial void OncapChanging(System.Nullable<int> value);
    partial void OncapChanged();
    #endregion
	
	public Course()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int course_id
	{
		get
		{
			return this._course_id;
		}
		set
		{
			if ((this._course_id != value))
			{
				this.Oncourse_idChanging(value);
				this.SendPropertyChanging();
				this._course_id = value;
				this.SendPropertyChanged("course_id");
				this.Oncourse_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_num", DbType="Int")]
	public System.Nullable<int> course_num
	{
		get
		{
			return this._course_num;
		}
		set
		{
			if ((this._course_num != value))
			{
				this.Oncourse_numChanging(value);
				this.SendPropertyChanging();
				this._course_num = value;
				this.SendPropertyChanged("course_num");
				this.Oncourse_numChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_title", DbType="VarChar(255)")]
	public string course_title
	{
		get
		{
			return this._course_title;
		}
		set
		{
			if ((this._course_title != value))
			{
				this.Oncourse_titleChanging(value);
				this.SendPropertyChanging();
				this._course_title = value;
				this.SendPropertyChanged("course_title");
				this.Oncourse_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instructor", DbType="VarChar(255)")]
	public string instructor
	{
		get
		{
			return this._instructor;
		}
		set
		{
			if ((this._instructor != value))
			{
				this.OninstructorChanging(value);
				this.SendPropertyChanging();
				this._instructor = value;
				this.SendPropertyChanged("instructor");
				this.OninstructorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cap", DbType="Int")]
	public System.Nullable<int> cap
	{
		get
		{
			return this._cap;
		}
		set
		{
			if ((this._cap != value))
			{
				this.OncapChanging(value);
				this.SendPropertyChanging();
				this._cap = value;
				this.SendPropertyChanged("cap");
				this.OncapChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
