//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.WCFNumberGuessingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFNumberGuessingService.INumberGuess")]
    public interface INumberGuess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuess/SecretNumber", ReplyAction="http://tempuri.org/INumberGuess/SecretNumberResponse")]
        int SecretNumber(int lower, int upper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuess/SecretNumber", ReplyAction="http://tempuri.org/INumberGuess/SecretNumberResponse")]
        System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuess/checkNumber", ReplyAction="http://tempuri.org/INumberGuess/checkNumberResponse")]
        string checkNumber(int userNum, int SecretNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuess/checkNumber", ReplyAction="http://tempuri.org/INumberGuess/checkNumberResponse")]
        System.Threading.Tasks.Task<string> checkNumberAsync(int userNum, int SecretNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberGuessChannel : WindowsFormsApplication1.WCFNumberGuessingService.INumberGuess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberGuessClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.WCFNumberGuessingService.INumberGuess>, WindowsFormsApplication1.WCFNumberGuessingService.INumberGuess {
        
        public NumberGuessClient() {
        }
        
        public NumberGuessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberGuessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberGuessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberGuessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SecretNumber(int lower, int upper) {
            return base.Channel.SecretNumber(lower, upper);
        }
        
        public System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper) {
            return base.Channel.SecretNumberAsync(lower, upper);
        }
        
        public string checkNumber(int userNum, int SecretNum) {
            return base.Channel.checkNumber(userNum, SecretNum);
        }
        
        public System.Threading.Tasks.Task<string> checkNumberAsync(int userNum, int SecretNum) {
            return base.Channel.checkNumberAsync(userNum, SecretNum);
        }
    }
}
